- Tokenization #Breaking text into individual words or characters — "Hello World" → ["Hello", "World"]
- Sequencing  #Converting words into numbers so the model can process them — "Hello" → 3, "World" → 7
- Padding # Making all sequences the same length by adding zeros — [3,7] → [0,0,3,7]
- Stemming #Cutting words to their root form roughly — "running" → "run", "flies" → "fli"
- Lemmatization #Converting words to their proper dictionary base form — "running" → "run", "flies" → "fly"

## Tokenization

In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [6]:
sentence = ['We like machine learning']
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentence)

The tokenizer scans all your text, counts how many times each word appears, then assigns 1 to the most common word, 2 to the next, and so on.

In [7]:
tokenizer.word_index

{'we': 1, 'like': 2, 'machine': 3, 'learning': 4}

In [8]:
# Reapeating words
sentence = ['we like machine learning and deep learning']
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentence)

tokenizer.word_index

{'learning': 1, 'we': 2, 'like': 3, 'machine': 4, 'and': 5, 'deep': 6}

In [9]:
# Tokenization is not case sensitive
# Tokenization removes special characters
sentence = ['@we like machine learning and deep LEARNING.....!!!']
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentence)

tokenizer.word_index

{'learning': 1, 'we': 2, 'like': 3, 'machine': 4, 'and': 5, 'deep': 6}

In [10]:
sentences = ['we are learning natural language processing',
             'we have learned how artificial neural networks work',
             'recurrent neural networks are mainly used for sequence data']

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
tokenizer.word_index

{'we': 1,
 'are': 2,
 'neural': 3,
 'networks': 4,
 'learning': 5,
 'natural': 6,
 'language': 7,
 'processing': 8,
 'have': 9,
 'learned': 10,
 'how': 11,
 'artificial': 12,
 'work': 13,
 'recurrent': 14,
 'mainly': 15,
 'used': 16,
 'for': 17,
 'sequence': 18,
 'data': 19}

## Sequencing

In [11]:
sentences = ['We are learning text preprocessing',
             'Tokenization refers to representing each word as a token',
             'Sequencing refers to representing text as a sequence of tokens',
             'Padding refers to adding zeros to sequences to make them all of same length']

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
tokenizer.word_index

{'to': 1,
 'refers': 2,
 'text': 3,
 'representing': 4,
 'as': 5,
 'a': 6,
 'of': 7,
 'we': 8,
 'are': 9,
 'learning': 10,
 'preprocessing': 11,
 'tokenization': 12,
 'each': 13,
 'word': 14,
 'token': 15,
 'sequencing': 16,
 'sequence': 17,
 'tokens': 18,
 'padding': 19,
 'adding': 20,
 'zeros': 21,
 'sequences': 22,
 'make': 23,
 'them': 24,
 'all': 25,
 'same': 26,
 'length': 27}

In [13]:
sequences = tokenizer.texts_to_sequences(sentences)
sequences

[[8, 9, 10, 3, 11],
 [12, 2, 1, 4, 13, 14, 5, 6, 15],
 [16, 2, 1, 4, 3, 5, 6, 17, 7, 18],
 [19, 2, 1, 20, 21, 1, 22, 1, 23, 24, 25, 7, 26, 27]]

In [15]:
tokenizer.texts_to_sequences(['Text preprocessing involves tokenization, sequencing and padding'])

[[3, 11, 12, 16, 19]]

In [16]:
# Out of vocabulary token
sentences = ['We are learning text preprocessing',
             'Tokenization refers to representing each word as a token',
             'Sequencing refers to representing text as a sequence of tokens',
             'Padding refers to adding zeros to sequences to make them all of same length']


tokenizer = Tokenizer(oov_token = '#OOV')
tokenizer.fit_on_texts(sentences)
tokenizer.word_index

{'#OOV': 1,
 'to': 2,
 'refers': 3,
 'text': 4,
 'representing': 5,
 'as': 6,
 'a': 7,
 'of': 8,
 'we': 9,
 'are': 10,
 'learning': 11,
 'preprocessing': 12,
 'tokenization': 13,
 'each': 14,
 'word': 15,
 'token': 16,
 'sequencing': 17,
 'sequence': 18,
 'tokens': 19,
 'padding': 20,
 'adding': 21,
 'zeros': 22,
 'sequences': 23,
 'make': 24,
 'them': 25,
 'all': 26,
 'same': 27,
 'length': 28}

In [17]:
tokenizer.texts_to_sequences(['Text preprocessing involves tokenization, Sequencing and Padding'])

[[4, 12, 1, 13, 17, 1, 20]]

## Padding

In [18]:
sentences = ['We like machine learning',
             'we are learning tokenization',
             'we are learning sequencing',
             'we are learning the padding technique',
             'machine learning and deep learning are fun']

tokenizer = Tokenizer(oov_token = '#OOV')
tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)
sequences

[[3, 6, 5, 2],
 [3, 4, 2, 7],
 [3, 4, 2, 8],
 [3, 4, 2, 9, 10, 11],
 [5, 2, 12, 13, 2, 4, 14]]

Model needs all inputs same size — zeros are just fillers, they mean nothing!

In [19]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_sequences = pad_sequences(sequences)
padded_sequences

array([[ 0,  0,  0,  3,  6,  5,  2],
       [ 0,  0,  0,  3,  4,  2,  7],
       [ 0,  0,  0,  3,  4,  2,  8],
       [ 0,  3,  4,  2,  9, 10, 11],
       [ 5,  2, 12, 13,  2,  4, 14]], dtype=int32)

In [20]:
padded_sequences = pad_sequences(sequences, padding = 'pre')
padded_sequences

array([[ 0,  0,  0,  3,  6,  5,  2],
       [ 0,  0,  0,  3,  4,  2,  7],
       [ 0,  0,  0,  3,  4,  2,  8],
       [ 0,  3,  4,  2,  9, 10, 11],
       [ 5,  2, 12, 13,  2,  4, 14]], dtype=int32)

In [21]:
padded_sequences = pad_sequences(sequences, padding = 'post')
padded_sequences

array([[ 3,  6,  5,  2,  0,  0,  0],
       [ 3,  4,  2,  7,  0,  0,  0],
       [ 3,  4,  2,  8,  0,  0,  0],
       [ 3,  4,  2,  9, 10, 11,  0],
       [ 5,  2, 12, 13,  2,  4, 14]], dtype=int32)

In [26]:
sentences = ['we like machine learning',
             'we are learning tokenization',
             'we are learning sequencing',
             'we are learning the padding technique',
             'machine learning and deep learninig are fun',
             'the purpose of text preprocessing is to give numerical representation to text data in order to be used for training']

tokenizer = Tokenizer(oov_token = '#OOV')
tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)
sequences

[[3, 9, 6, 2],
 [3, 4, 2, 10],
 [3, 4, 2, 11],
 [3, 4, 2, 7, 12, 13],
 [6, 2, 14, 15, 16, 4, 17],
 [7, 18, 19, 8, 20, 21, 5, 22, 23, 24, 5, 8, 25, 26, 27, 5, 28, 29, 30, 31]]

In [27]:
import numpy as np
np.set_printoptions(linewidth = 200)

In [28]:
padded_sequences = pad_sequences(sequences, padding = 'post')
padded_sequences

array([[ 3,  9,  6,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 3,  4,  2, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 3,  4,  2, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 3,  4,  2,  7, 12, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 6,  2, 14, 15, 16,  4, 17,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 7, 18, 19,  8, 20, 21,  5, 22, 23, 24,  5,  8, 25, 26, 27,  5, 28, 29, 30, 31]], dtype=int32)

In [29]:
padded_sequences = pad_sequences(sequences, padding = 'post', maxlen = 8)
padded_sequences

array([[ 3,  9,  6,  2,  0,  0,  0,  0],
       [ 3,  4,  2, 10,  0,  0,  0,  0],
       [ 3,  4,  2, 11,  0,  0,  0,  0],
       [ 3,  4,  2,  7, 12, 13,  0,  0],
       [ 6,  2, 14, 15, 16,  4, 17,  0],
       [25, 26, 27,  5, 28, 29, 30, 31]], dtype=int32)

In [30]:
padded_sequences = pad_sequences(sequences, padding = 'post', maxlen = 8, truncating = 'pre')
padded_sequences

array([[ 3,  9,  6,  2,  0,  0,  0,  0],
       [ 3,  4,  2, 10,  0,  0,  0,  0],
       [ 3,  4,  2, 11,  0,  0,  0,  0],
       [ 3,  4,  2,  7, 12, 13,  0,  0],
       [ 6,  2, 14, 15, 16,  4, 17,  0],
       [25, 26, 27,  5, 28, 29, 30, 31]], dtype=int32)

In [31]:
padded_sequences = pad_sequences(sequences, padding = 'post', maxlen = 8, truncating = 'post')
padded_sequences

array([[ 3,  9,  6,  2,  0,  0,  0,  0],
       [ 3,  4,  2, 10,  0,  0,  0,  0],
       [ 3,  4,  2, 11,  0,  0,  0,  0],
       [ 3,  4,  2,  7, 12, 13,  0,  0],
       [ 6,  2, 14, 15, 16,  4, 17,  0],
       [ 7, 18, 19,  8, 20, 21,  5, 22]], dtype=int32)

---------------------------
---------------------------


In [32]:
sentences = ['we like machine learning',
             'we are learning tokenization',
             'we are learning sequencing',
             'we are learning the padding technique',
             'machine learning and deep learninig are fun',
             'the purpose of text preprocessing is to give numerical representation to text data']

tokenizer = Tokenizer(oov_token = '#OOV')                     # Create a tokenizer object
tokenizer.fit_on_texts(sentences)                             # Tokenization
sequences = tokenizer.texts_to_sequences(sentences)           # Sequencing
padded_sequences = pad_sequences(sequences, maxlen = 8)       # Padding
padded_sequences

array([[ 0,  0,  0,  0,  3,  9,  5,  2],
       [ 0,  0,  0,  0,  3,  4,  2, 10],
       [ 0,  0,  0,  0,  3,  4,  2, 11],
       [ 0,  0,  3,  4,  2,  6, 12, 13],
       [ 0,  5,  2, 14, 15, 16,  4, 17],
       [21,  8, 22, 23, 24,  8,  7, 25]], dtype=int32)

## ======================================================================
----

## Stemming

In [33]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
stemmer.stem('breaking')

'break'

In [34]:
stemmer.stem('Writing')

'write'

In [35]:
stemmer.stem('troubling')

'troubl'

In [36]:
print(stemmer.stem('breaks'))
print(stemmer.stem('breaking'))
print(stemmer.stem('broke'))
print(stemmer.stem('broken'))
print(stemmer.stem('changes'))
print(stemmer.stem('changed'))
print(stemmer.stem('changing'))
print(stemmer.stem('writes'))
print(stemmer.stem('writing'))
print(stemmer.stem('wrote'))
print(stemmer.stem('running'))
print(stemmer.stem('ran'))
print(stemmer.stem('run'))
print(stemmer.stem('trouble'))
print(stemmer.stem('troubling'))
print(stemmer.stem('troubles'))
print(stemmer.stem('troubled'))
print(stemmer.stem('cats'))
print(stemmer.stem('knives'))
print(stemmer.stem('leaves'))
print(stemmer.stem('jumping'))
print(stemmer.stem('jumped'))

break
break
broke
broken
chang
chang
chang
write
write
wrote
run
ran
run
troubl
troubl
troubl
troubl
cat
knive
leav
jump
jump


## Lemmatization

wordnet is a large English dictionary database that NLTK needs to perform Lemmatization — without downloading it, the lemmatizer won't know what the base form of any word is.

In [37]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\rehan.qureshi\AppData\Roaming\nltk_data...


True

In [38]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
lemmatizer.lemmatize('breaks')

'break'

In [39]:
lemmatizer.lemmatize('break', pos = 'v')

'break'

In [ ]:
print(lemmatizer.lemmatize('breaks',  pos = 'v'))
print(lemmatizer.lemmatize('breaking',  pos = 'v'))
print(lemmatizer.lemmatize('broke',  pos = 'v'))
print(lemmatizer.lemmatize('broken',  pos = 'v'))
print(lemmatizer.lemmatize('changes',  pos = 'v'))
print(lemmatizer.lemmatize('changed', pos = 'v'))
print(lemmatizer.lemmatize('changing', pos = 'v'))
print(lemmatizer.lemmatize('writes', pos = 'v'))
print(lemmatizer.lemmatize('writing', pos = 'v'))
print(lemmatizer.lemmatize('wrote', pos = 'v'))
print(lemmatizer.lemmatize('running', pos = 'v'))
print(lemmatizer.lemmatize('ran', pos = 'v'))
print(lemmatizer.lemmatize('run', pos = 'v'))
print(lemmatizer.lemmatize('trouble', pos = 'v'))
print(lemmatizer.lemmatize('troubling', pos = 'v'))
print(lemmatizer.lemmatize('troubles', pos = 'v'))
print(lemmatizer.lemmatize('troubled', pos = 'v'))
print(lemmatizer.lemmatize('cats', pos = 'v'))
print(lemmatizer.lemmatize('knives'))
print(lemmatizer.lemmatize('leaves'))
print(lemmatizer.lemmatize('jumping', pos = 'v'))
print(lemmatizer.lemmatize('jumped', pos = 'v'))

break
break
break
break
change
change
change
write
write
write
run
run
run
trouble
trouble
trouble
trouble
cat
knife
leaf
jump
jump


: 